common:
  vpn_cidr: "10.1.0.0/16"

workspaces:
  nonprod-us-east-1-default:
    aws:
      account_id: 123456789
      region: us-east-1
    account_name: nonprod
    project_name: test
    project_name_prefix: test
    vpc_id: "vpc-07e3c626b44400ee2"
    subnet_ids: ["subnet-0d54d4e103d8c08c0","subnet-036bc6c5e8973f10c"]
    jenkins_version: "2.387"
    custom_cidr: ""
    assign_public_ip: true
