common:
  vpn_cidr: "10.1.0.0/16"

workspaces:
  nonprod-us-east-1-default:
    aws:
      account_id: 123456789
      region: us-east-1
    account_name: nonprod
    project_name: test
    project_name_prefix: test
    vpc_id: "vpc-0a760e3212e001050"
    subnet_ids: ["subnet-01c3a3de9aec3013a","subnet-01c3a3de9aec3013a"]
    jenkins_version: "2.387"
    custom_cidr: ""
    assign_public_ip: true
